# Generated by Django 4.2.6 on 2023-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist_comment_bid_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_id',
        ),
    ]
