# Generated by Django 4.2.6 on 2023-11-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
